public class Campaignobjectapex {
    public string campaignname='vrcollege';
    public boolean campaigntypeisactive=true;
    public integer NumSentinCampaign =45000;
    public boolean isamountreceived= true;
    public decimal revenue	=35000;
    public date campaignstartdate=system.today();
    public date campaignenddate=system.today()+10;
    public string campaigncurrency='USD';
    public id recordid='7015e000000lM0d';
    
}