public class Innerapexclasses {
    public string str='swapna';
    public account acc=new account();
    public Innerapexclasses(){
      Opportunity op=new Opportunity(name='sam',stagename='prospect');
         system.debug('op..'+op);
        acc.name='shiva';
        acc.Rating='warm';
        system.debug('acc..'+acc);
    } 
    public void Innerapexclasses(){
       string account='saleem';
        lead ld =new lead();
        
    }
    public sobject method () {
       Opportunity op =new Opportunity();
       system.debug('op==='+ op);
      return null;


    }
        
   }