public class Leadapexclass {
public string leadname='swapna';
public integer nooflocations=46;
public boolean isactive=true;
public decimal annualrevenue=78000;
    public Leadapexclass(string rating){
        system.debug('leadname....'+ leadname);
         system.debug('rating....'+ rating);
        mymethod(56);
    }
    public void mymethod(integer noofemployees){
        integer nooflocations=89;
        system.debug('nooflocations....'+ nooflocations);
         system.debug('noofemployees....'+ noofemployees);
         system.debug('isactive....'+ isactive);
         system.debug('annualrevenue....'+ annualrevenue);
        
    }


}