public class Leadobjectapex {
    public string leadname='Anusha';
    public boolean campaigntypeisactive=true;
    public string phonenumber ='3145502156';
    public boolean isamountreceived= true;
    public decimal annualrevenue	=35000;
    public date leadcreationdate=system.today();
    public string leadstatus='opennot-contracted';
    public id recordid='00Q5e00000AtRhb';
    public integer noofemployees =4500;
    
    
}