public class Logic4t {
    public string country ='usa';
    public string state='Georgia';
    public account acc =new account ();
    
    public Logic4t (){
        if(country=='usa'){
          system.debug('country=='+country); 
            
            
        }else{
            country='india';
            if (country=='india' ){
             system.debug('country=='+country); 
                }
        }
        
       
    }

}