public class Utilityclasses {
    public set<lead>leadset = new set<lead>();
    public set<integer>empcount=new set<integer>{45,67,78,89,90};
        
        public  Utilityclasses(){
         system.debug('empcount=='+empcount); 
            }
    public void method(){
       string leadname='raju' ;
        campaign camp=new campaign();
        list<contact>conlist=new list<contact>();
        set<string>nameset= new  set<string>{'madhu','radha','keerthi','somu'};
        map<string,integer> stdmap=new   map<string,integer>();
         system.debug(' leadname=='+ leadname); 
         system.debug('camp=='+camp); 
         system.debug('conlist=='+conlist); 
         system.debug('nameset=='+nameset); 
         system.debug('stdmap=='+stdmap); 
        
        
    }

}